name: Arquitetura

on:
  push:
    branches:
      - squadPadroes
  pull_request:
    branches:
      - squadPadroes

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
         python-version: '3.11'

      - name: Execution test
        run: python -m compileall -q src

      - name: Install import linter
        run: |
          python -m pip install --upgrade pip
          pip install import-linter==2.13

      - name: Check domain
        run: lint-imports
        env:
          PYTHONPATH: src
